# Build settings
markdown: kramdown

# Setup
baseurl: "" # the subpath of your site, e.g. /blog/

title:            Jonathan Ilano
tagline:          Full Stack Web Developer
description:      Personal site of web developer Jonathan Ilano.
url:              jonathanilano.com

author:
  name:           Jonathan
  fullname:       Jonathan Ilano
  email:          hi@jonathanilano.com
  encoded:        "&#104;&#105;&#064;&#106;&#111;&#110;&#097;&#116;&#104;&#097;&#110;&#105;&#108;&#097;&#110;&#111;&#046;&#099;&#111;&#109;"
  avatar:         https://avatars2.githubusercontent.com/u/6225434?v=3&s=460
  twitter:        https://twitter.com/jonilano
  github:         https://github.com/jonilano
  facebook:       https://facebook.com/jonilano	


shortbio:
  firstline:      I'm a self-taught full stack
  secondline:     web developer.


exclude:          [CNAME, Gemfile, Gemfile.lock, Makefile, README.md, vendor]