# Build settings
markdown: kramdown

# Setup
baseurl: "" # the subpath of your site, e.g. /blog/

title:            Jonathan Ilano
tagline:          Full Stack Web Developer
description:      Personal site of web developer Jonathan Ilano.
url:              jonathanilano.com

author:
  name:           Jonathan
  fullname:       Jonathan Ilano
  email:          hi@jonathanilano.com
  avatar:         https://avatars2.githubusercontent.com/u/6225434?v=3&s=460
  twitter:        https://twitter.com/jonilano
  github:         https://github.com/jonilano
  codepen:        http://codepen.io/jonilano
  bio:            I'm a self-taught full stack web developer.

exclude:          [CNAME, Gemfile, Gemfile.lock, Makefile, README.md, vendor]
